# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Cross-platform build and release

on:
  release:
    types: [created]

jobs:
  build-linux-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller main.py --onefile --name pgtool
        # 生成带平台名称的可执行文件
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          mv dist/pgtool dist/pgtool-linux-amd64
        else
          mv dist/pgtool dist/pgtool-macos-arm64
        fi

    - name: Upload platform binary
      uses: softprops/action-gh-release@v1
      with:
        files: dist/pgtool-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload Windows binary
      uses: softprops/action-gh-release@v1
      with:
        files: pgtool-windows-amd64/pgtool.exe
        name: pgtool-windows-amd64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



